-- Migration: plan sharing & real-time sync tables
-- Run in Supabase SQL editor or via: supabase db push
--
-- These tables back the invite-code sharing flow and Supabase Realtime sync
-- used by PlanSyncManager (planSync.ts) on the frontend.

-- ── roam_plans ─────────────────────────────────────────────────────────────────
-- Cloud mirror of each user's offline plan record.
-- Only the lightweight "recipe" is stored — no zip blobs or tile packs.

create table if not exists public.roam_plans (
  plan_id        uuid primary key,
  owner_id       uuid not null references auth.users(id) on delete cascade,
  route_key      text not null,
  label          text,
  preview        jsonb,           -- OfflinePlanPreview: stops, geometry, bbox, distance, duration, profile
  manifest_meta  jsonb,           -- corridor/places/traffic/hazards status + keys
  created_at     timestamptz not null default now(),
  updated_at     timestamptz not null default now()
);

create index if not exists roam_plans_owner_idx on public.roam_plans (owner_id);

alter table public.roam_plans enable row level security;

-- ── roam_plan_members ──────────────────────────────────────────────────────────
-- Tracks who has access to each plan and their role.
-- The composite PK matches planSync's onConflict: "plan_id,user_id".

create table if not exists public.roam_plan_members (
  plan_id   uuid not null references public.roam_plans(plan_id) on delete cascade,
  user_id   uuid not null references auth.users(id) on delete cascade,
  role      text not null check (role in ('owner', 'editor')),
  joined_at timestamptz not null default now(),
  primary key (plan_id, user_id)
);

alter table public.roam_plan_members enable row level security;

-- ── Helper: check membership without triggering RLS ────────────────────────────
-- Used by roam_plans policies to avoid cross-table RLS recursion.

create or replace function public.is_plan_member(p_plan_id uuid, p_user_id uuid)
returns boolean
language plpgsql
stable
security definer
set search_path = public
as $$
begin
  return exists (
    select 1 from public.roam_plan_members
    where plan_id = p_plan_id
      and user_id = p_user_id
  );
end;
$$;

-- ── roam_plans RLS ─────────────────────────────────────────────────────────────

drop policy if exists "Owner can manage own plans" on public.roam_plans;
drop policy if exists "Members can read shared plans" on public.roam_plans;
drop policy if exists "Editors can update shared plans" on public.roam_plans;

create policy "Owner can manage own plans"
  on public.roam_plans for all
  using (auth.uid() = owner_id)
  with check (auth.uid() = owner_id);

create policy "Members can read shared plans"
  on public.roam_plans for select
  using (public.is_plan_member(plan_id, auth.uid()));

create policy "Editors can update shared plans"
  on public.roam_plans for update
  using (public.is_plan_member(plan_id, auth.uid()));

-- ── roam_plan_members RLS ──────────────────────────────────────────────────────

drop policy if exists "Members can read plan memberships" on public.roam_plan_members;
drop policy if exists "Users can read own memberships" on public.roam_plan_members;
drop policy if exists "Owners can read all plan members" on public.roam_plan_members;
drop policy if exists "Users can join plans" on public.roam_plan_members;
drop policy if exists "Owners can manage members" on public.roam_plan_members;

create policy "Users can read own memberships"
  on public.roam_plan_members for select
  using (auth.uid() = user_id);

create policy "Owners can read all plan members"
  on public.roam_plan_members for select
  using (
    exists (
      select 1 from public.roam_plans
      where roam_plans.plan_id = roam_plan_members.plan_id
        and roam_plans.owner_id = auth.uid()
    )
  );

create policy "Users can join plans"
  on public.roam_plan_members for insert
  with check (auth.uid() = user_id);

create policy "Owners can manage members"
  on public.roam_plan_members for delete
  using (
    exists (
      select 1 from public.roam_plans
      where roam_plans.plan_id = roam_plan_members.plan_id
        and roam_plans.owner_id = auth.uid()
    )
  );

-- ── roam_plan_invites ──────────────────────────────────────────────────────────
-- Short-lived invite codes for plan sharing.
-- Code is the 6-char alphanumeric string generated by planSync._generateCode().

create table if not exists public.roam_plan_invites (
  code        text primary key,
  plan_id     uuid not null references public.roam_plans(plan_id) on delete cascade,
  created_by  uuid not null references auth.users(id) on delete cascade,
  expires_at  timestamptz,
  max_uses    integer not null default 5,
  uses        integer not null default 0,
  created_at  timestamptz not null default now()
);

create index if not exists roam_plan_invites_plan_id_idx
  on public.roam_plan_invites (plan_id);

alter table public.roam_plan_invites enable row level security;

drop policy if exists "Authenticated users can read invites" on public.roam_plan_invites;
drop policy if exists "Creator can create invites" on public.roam_plan_invites;
drop policy if exists "Authenticated users can update invite uses" on public.roam_plan_invites;

create policy "Authenticated users can read invites"
  on public.roam_plan_invites for select
  using (auth.uid() is not null);

create policy "Creator can create invites"
  on public.roam_plan_invites for insert
  with check (auth.uid() = created_by);

create policy "Authenticated users can update invite uses"
  on public.roam_plan_invites for update
  using (auth.uid() is not null);

-- ── Enable Supabase Realtime on roam_plans ─────────────────────────────────────
-- planSync subscribes to postgres_changes on this table for live collaboration.
-- Guarded: skip if already a member of the publication.

do $$
begin
  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'roam_plans'
  ) then
    alter publication supabase_realtime add table public.roam_plans;
  end if;
end $$;
